Fix TypeError TypeError: randint() missing 1 required positional argument: 'b' The Type Error also causes IndexError: list index out of range on line utils.blit_offset('status/' + self.compare_list[num][x],
To Reproduce the error: Input one numberwhen on Level `Easy` Then shift the level to `Hard`. The Error occurs